# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f3abd276eaa054ff0b66839fe8cfaca2d9256f60beeb4df8e997db1cb82b86f899abdd8a23079908c44861a0291d8614a454fab8e52a0c9ae57851a7c1f851

test:
  secret_key_base: 837509fc315865f7850eb1d60f6234339a02953b2d74540899f297684db1846cf61ed9644663aee7ec9d8ea5ded2af99552580c0204479c62489c15c7ad3e1a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
